### ISSUE TITLE
Footer block

### ISSUE THREAD

**Issue by caecilian** [arribada/horizon-gui#16]
Logo

**Comment by Flustered** [comment]
Added to all pages except the homepage / landing page

Need content.

**Comment by Flustered** [comment]
Added 

- GUI Version
- Hardware Version
- System Time
- Hub Time

**Comment by FilipNest** [comment]
Need footer content from arribada

**Comment by Flustered** [comment]
Added file:
templates/client_footer.html to contain this.  

Styled with class="clientFooter"
