### ISSUE TITLE
Confirm messages on saving actions throughout system

### ISSUE THREAD

**Issue by caecilian** [arribada/horizon-gui#34]
Especially in any case where risk of saving same name.

**Comment by Flustered** [comment]
Have implemented a standard user message area using sessions... Need to implement it in specific cases... (currently only works for sync clock.)

**Comment by Flustered** [comment]
Ongoing: 

- [x] Delete Preset

- [x] Save Preset

- [x] Apply Preset

- [x] Delete Preset

- [x] Save Config

- [x] Delete Log

- [x] Log Imported

- [x] Scan for Updates

- [x] Erase Logs

- [x] Erase Device
