### ISSUE TITLE
IDs pushing UI elements out of alignment

### ISSUE THREAD

**Issue by pcprince** [arribada/horizon-gui#5]
When a device is assigned an extremely long ID, the radio button selecting it gets pushed out the top of the table.

**Comment by pcprince** [comment]
I was wrong, the radio buttons stick out the top of the UI regardless of ID length. That probably needs to be fixed.

**Comment by Flustered** [comment]
@pcprince This is all due to change with the hardware IDs. I haven't installed the latest firmware yet..  What format will these numbers be?

**Comment by Flustered** [comment]
Can we close this?

**Comment by pcprince** [comment]
Yes. Although I think we may need to think about the design of the table columns when they're not selected though. It looks like the UI is broken as the radio button pokes out the top of the table. It looks fine when the tag is selected.
