### ISSUE TITLE
Make names of functions configurable for between v2 and v3

### ISSUE THREAD

**Issue by caecilian** [arribada/horizon-gui#55]

**Comment by caecilian** [comment]
For where names have changes between versions?
e.g. set time

**Comment by Flustered** [comment]
Added to constants.py

# device tool version / directory
DEVICE_HARDWARE_VERSION = "v2.0"  # for firmware 11 hardware 2
#DEVICE_HARDWARE_VERSION = "v3.0" # for firmware ?? hardware 3

Then there are 2 sets of tool commands in 
/hardwareVersion/v2.0/devicefunctions.py and 
/hardwareVersion/v3.0/devicefunctions.py
