### ISSUE TITLE
Investigate why CSV downloading sometimes fails

### ISSUE THREAD

**Issue by al2k** [arribada/horizon-gui#89]

**Comment by adanger** [comment]
Expectation 1: A .cvs file of the device logs can be downloaded by clicking on the “Download: Separated CSV” link in the GUI

Actual 1: A web browser tab immediately opens with an Internal Server error. No file appears for download.

![image](https://user-images.githubusercontent.com/53336446/112021255-b3ea5980-8af6-11eb-9a35-8888e0574196.png)

Expectation 2: A .cvs file of the device logs can be downloaded by clicking on the “Download: Separated CSV” link in the GUI

Actual 2: Another user has reported that when she clicks to download the .csv file, she gets a message saying “waiting for 10.0.60.1” on a loading tab that has persisted for 15 minutes before she gave up and closed the tab

![image](https://user-images.githubusercontent.com/53336446/112021316-cb294700-8af6-11eb-83a2-210b68da9505.png)

**Comment by al2k** [comment]
We checked this. It's the CSV convert that is failing.

It doesn't like any log that doesn't go Timestamp, GPS, Timestamp GPS etc...

{"Timestamp": {"timestamp": 0}}
{"GPSPosition": {"iTOW": 149342000, "longitude": -0.8050258, "latitude": 51.0782563, "height": 1.107, "accuracyHorizontal": 10.222, "accuracyVertical": 3.933}}
{"Timestamp": {"timestamp": 0}}
{"GPSPosition": {"iTOW": 149342000, "longitude": -0.8050258, "latitude": 51.0782563, "height": 1.107, "accuracyHorizontal": 10.222, "accuracyVertical": 3.933}}
{"Timestamp": {"timestamp": 0}}

If it's:

{"Timestamp": {"timestamp": 0}}
{"Startup": {"cause": "0x0"}}
{"Timestamp": {"timestamp": 0}}
{"Startup": {"cause": "0x1"}}
{"Startup": {"cause": "0x1"}}

Then it fails, so we need to skip and bypass this



  File "horizon_gui.py", line 425, in log_to_split_csv_files
    datePart = json.loads(logEntry[0])["Timestamp"]["timestamp"]
KeyError: 'Timestamp'

**Comment by adanger** [comment]
I have seen something slightly different when my CSV download fails:

Here is an example of the first lines of a .json log that failed to export a CSV file and threw the internal server error:

{"Timestamp": {"timestamp": 0}}
{"Startup": {"cause": "0x0"}}
{"Timestamp": {"timestamp": 4}}
{"BatteryCharge": {"charge": 100}}
{"Timestamp": {"timestamp": 30}}
{"GPSOn": {}}
{"Timestamp": {"timestamp": 30}}
{"BatteryVoltage": {"voltage": 4719}}
{"Timestamp": {"timestamp": 1616511541}}
{"GPSPosition": {"iTOW": 226758010, "longitude": -84.1012935, "latitude": 10.008342899999999, "height": 0.0, "accuracyHorizontal": 58.58, "accuracyVertical": 1.414}}

The error I get in Putty is:
File "horizon_gui.py", line 425, in log_to_split_csv_files
    datePart = json.loads(logEntry[0])["Timestamp"]["timestamp"]
KeyError: 'Timestamp'

Here is an example of .json logs where I was able to successfully download a CSV file:

{"Timestamp": {"timestamp": 0}}
{"Startup": {"cause": "0x0"}}
{"Timestamp": {"timestamp": 4}}
{"BatteryCharge": {"charge": 100}}
{"Timestamp": {"timestamp": 30}}
{"GPSOn": {}}
{"Timestamp": {"timestamp": 30}}
{"BatteryVoltage": {"voltage": 4719}}
{"Timestamp": {"timestamp": 1616511541}}
{"GPSPosition": {"iTOW": 226758010, "longitude": -84.1012935, "latitude": 10.008342899999999, "height": 0.0, "accuracyHorizontal": 58.58, "accuracyVertical": 1.414}}
{"Timestamp": {"timestamp": 1616511541}}

These two logs start identically. The only thing I did differently between the two deployments was log clearing. 
If I clear all of the previous logs on the tag, I’m able to download the CSV file after the next deployment. If I do not clear the logs from the tag before re-deploying, I’m unable to download the CSV files for the old deployment or the deployment that just finished once the tag is re-attached to the HUB.

**Comment by adanger** [comment]
I tried a new, lonrroger tag deployment this morning. Prior to deployment, I cleared all of the logs off the tag and then reconfigured and took it out for about 30min.

I connected the tag to the HUB and tried downloading the .cvs files through the GUI. I also logged into Putty so I could catch any error codes. 

I got an immediate internal server error when I tried downloading, but this time I found different error codes in the script. In the screenshot below, the left image is the log preview in the GUI and the right image shows the multiple errors thrown when I tried to download the .csv file.

![multi_error_csv_download](https://user-images.githubusercontent.com/53336446/112352288-407c4f80-8c90-11eb-93d8-0a6097063379.png)

**Comment by Flustered** [comment]
The original code expected pairs of TIMESTAMP and DATA records, so they could be merged and the timestamp added to the data record.

I have refactored this code (pushed up to repo) so manually matches records together or creates blank timestamp data where there is not TIMESTAMP record.

Attachments: 

[TESTING_LOG_DATA.zip](https://github.com/arribada/horizon-gui/files/6206029/TESTING_LOG_DATA.zip)
Using this Test data I got the following logs download

[separated_logs_68509d3879c0b05a.zip](https://github.com/arribada/horizon-gui/files/6206032/separated_logs_68509d3879c0b05a.zip)

Note: Line 7 in the test data is a data only record, no timestamp.  This appears in Startup.csv
There is one GPS position record which extracts as


iTOW | longitude | latitude | height | accuracyHorizontal | accuracyVertical | time
4.25E+08 | -0.80521 | 51.07888 | 0 | 1924.74 | 484.169 | 2020-12-24:21-57-18

I also added into the CSV data when timestamps are missing or zero value and where a DATA record has no payload (i.e. GPS on / Off)

**Comment by Flustered** [comment]
There are still issues, in that old download data remains in for each device. This folder needs to be deleted BEFORE download starts.

See https://github.com/arribada/horizon-gui/issues/91

**Comment by adanger** [comment]
Fixed with v4.0.3. It was an issue with the .csv not being created correctly if the tag was turned off in the middle of writing data and the data bunch was incomplete (i.e. timestamp + data). This has been fixed so the .csv files will be created even if all the data expected is not there.
